"""creating the db

Revision ID: 1f35a9f6108b
Revises: 606c710e200b
Create Date: 2022-02-13 09:20:06.943295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1f35a9f6108b"
down_revision = "606c710e200b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.create_index(
            "idx_zip_code_city_street_house_no",
            ["postal_code", "city", "street", "house_no_min", "house_no_max"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.drop_index("idx_zip_code_city_street_house_no")

    # ### end Alembic commands ###
