"""creating the db

Revision ID: 606c710e200b
Revises: 
Create Date: 2022-02-13 09:13:57.145610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "606c710e200b"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("postal_code", sa.Integer(), nullable=False),
        sa.Column("city", sa.String(length=50), nullable=False),
        sa.Column("street", sa.String(length=100), nullable=False),
        sa.Column("house_no_min", sa.Integer(), nullable=False),
        sa.Column("house_no_max", sa.Integer(), nullable=False),
        sa.Column("unit_price", sa.Float(), nullable=False),
        sa.Column("grid_fee", sa.Float(), nullable=False),
        sa.Column("kwh_price", sa.Float(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_prices_timestamp"), ["timestamp"], unique=False
        )

    op.create_table(
        "revoked_token_model",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("jti", sa.String(length=120), nullable=True),
        sa.Column("date_revoked", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=64), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("join_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("username"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_table("revoked_token_model")
    with op.batch_alter_table("prices", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_prices_timestamp"))

    op.drop_table("prices")
    # ### end Alembic commands ###
